task1
ok-technopolis-autumn-2022/Elizaveta_Voronina pull request #1
Opened 2022-10-01 20:38 UTC by charlsraven

html added

2022-10-03 08:01 UTC, fromanywhere requested changes

2022-10-03 08:01 UTC, fromanywhere commented on hw1.html
> +    <div class="header logo">
Здесь лучше использовать больше семантической разметки

2022-10-03 08:01 UTC, fromanywhere commented on hw1.html
> +                        <input type="submit">
Ваша идея понятна
Для того, чтобы Вам было проще в следующих ДЗ, давайте всё же поставим здесь чекбокс

2022-10-03 08:01 UTC, fromanywhere commented on hw1.html
> +                    <div class="close">
Здесь точно другой тег

2022-10-03 08:01 UTC, fromanywhere commented on hw1.html
> +                <button placeholder="All"></button>
Мы с лектором поговорили и решили, что будет лучше, если в этом месте будет использоваться другое решение (расскажут сегодня. Если не расскажут, нужно будет задать лектору вопрос о причинах)

2022-10-10 08:57 UTC, fromanywhere approved these changes
Тут есть весьма оригинальные авторские решения, но работать будет

2022-10-10 08:57 UTC, fromanywhere commented on hw1.html
> +            <button class="select_all" data-message="select all">select all</button>
data-message?

2022-10-10 08:57 UTC, fromanywhere commented on hw1.html
> +            <label for="new">What needs to be done?</label>
ладно, но проще было положить через атрибут placeholder

2022-10-10 11:10 UTC, charlsraven commented on hw1.html
> +            <label for="new">What needs to be done?</label>
да, проще, но wave ругается, что это не супер хороший подход

2022-10-10 11:14 UTC, merged

2022-10-10 11:17 UTC, fromanywhere commented on hw1.html
> +            <label for="new">What needs to be done?</label>
а как именно ругается?

2022-10-10 11:45 UTC, charlsraven commented on hw1.html
> +            <label for="new">What needs to be done?</label>
перепробовала несколько комбинаций, оказалось, ругался конкретно на то, что есть пустые button, но с placeholder. могу исправить -- код гораздо короче

2022-10-10 11:56 UTC, charlsraven commented on hw1.html
> +            <label for="new">What needs to be done?</label>
если вносить изменения, то в main или в task1?

2022-10-10 13:20 UTC, fromanywhere commented on hw1.html
> +            <label for="new">What needs to be done?</label>
в main