update html + draft css
ok-technopolis-autumn-2022/Elizaveta_Voronina pull request #2
Opened 2022-10-16 17:52 UTC by charlsraven

2022-10-17 07:48 UTC, fromanywhere commented on css/styles.css
> +    height: 100%;
Это хорошо
По ширине тоже нужно будет растянуть

2022-10-17 07:49 UTC, fromanywhere commented on css/styles.css
> +    overflow-y: auto;
чтобы скролл на контейнере появился, ему нужно будет ограничить высоту

2022-10-24 07:38 UTC, fromanywhere requested changes

2022-10-24 07:38 UTC, fromanywhere commented on css/styles.css
> +    height: 60px;
что будет, если текста будет много?

2022-10-24 07:38 UTC, fromanywhere commented on index.html
> +<!DOCTYPE html>
Вообще предполагалось, что Вы работаете поверх первой домашки

2022-10-24 07:38 UTC, fromanywhere commented on index.html
> +                    <button placeholder="Clear complited">Clear completed</button>
placeholder у button не бывает

2022-10-24 07:38 UTC, fromanywhere commented on css/styles.css
> +    height: 12px;
<img width="133" alt="image" src="https://user-images.githubusercontent.com/1042969/197472033-769b6b3f-299c-46a0-8203-4c78c01caeae.png">
Увеличиваем зону клика

2022-10-24 07:38 UTC, fromanywhere commented on css/styles.css
> +    width: 20px;
Аналогично 
<img width="83" alt="image" src="https://user-images.githubusercontent.com/1042969/197472248-0e3cbebe-435a-44f5-b2aa-1551b3880f09.png">

2022-10-24 07:38 UTC, fromanywhere commented on index.html
> +                        <input type="radio" id="sorting-complited" value="Complited">
<img width="230" alt="image" src="https://user-images.githubusercontent.com/1042969/197472468-a5fd42e5-c0da-43e8-9145-27bcc8c9e10d.png">

2022-10-24 07:38 UTC, fromanywhere commented on css/styles.css
> +    height: 60px;
<img width="618" alt="image" src="https://user-images.githubusercontent.com/1042969/197472597-c3f54193-7663-4138-840c-f695d8795014.png">

2022-10-24 17:56 UTC, charlsraven commented on index.html
> +<!DOCTYPE html>
у меня слетел файл при переименовании (брейкетс не подгружал html, если он не был назван index)

2022-10-31 16:10 UTC, fromanywhere approved these changes
Зачел

2022-10-31 16:10 UTC, fromanywhere commented on css/styles.css
> +    display: flex;
Может быть вот так 
<img width="674" alt="image" src="https://user-images.githubusercontent.com/1042969/199055059-a37b3943-188c-4989-80ec-bb3aea1f5f6c.png">

2022-10-31 16:12 UTC, merged